// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivzlusheqenlzvdirnxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2emx1c2hlcWVubHp2ZGlybnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNjc4NDcsImV4cCI6MjA4Njk0Mzg0N30.RZginthfFGkguXKow9Ue95Tt_87CUTcMkFvxiqJOuOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});